CALL_HOME_URL = 'https://r4sir2jo37.execute-api.us-east-2.amazonaws.com/testing/'
CALL_HOME_RECORD_FILE = 'ccm_record.txt'
CALL_HOME_USER_CONFIG_FILE = 'ccm_config.json'
CALL_HOME_PUBLISH_MESSAGE_MAX_QUEUE_SIZE = 100
CALL_HOME_MAX_WORKERS_THREADS = 5
CALL_HOME_MODEL_RUN_COUNT_TIME_SECS = 300 
CALL_HOME_REQ_STOP_MAX_COUNT = 3 
