FROM ubuntu:18.04

RUN apt-get update && \
    apt-get install -y python3 python3-dev python3-distutils wget curl ca-certificates \
    libtinfo-dev zlib1g-dev build-essential libedit-dev libxml2-dev \
    antlr4 gnupg git clang-format-10 \
    && rm -rf /var/lib/apt/lists/* \
    && curl https://bootstrap.pypa.io/pip/3.6/get-pip.py -o get-pip.py && python3 get-pip.py && rm get-pip.py \
    && rm -rf /root/.cache/pip

RUN pip3 install -U pip setuptools wheel

RUN pip3 install Cython numpy sklearn pytest

RUN wget https://cmake.org/files/v3.21/cmake-3.21.4-linux-x86_64.sh \
    && bash cmake-3.21.4-linux-x86_64.sh --skip-license --prefix=/usr/local

ENV PYTHON_COMMAND=python3

WORKDIR /workspace
