FROM ubuntu:18.04

RUN apt-get update && \
    apt-get install -y python3 python3-dev python3-setuptools curl ca-certificates build-essential && \
    apt-get install -y gcc libtinfo-dev zlib1g-dev build-essential cmake libedit-dev libxml2-dev && \
    apt-get install -y antlr4 && \
    apt-get install -y python3-pip && \
    apt-get install -y gnupg && \
    apt-get install -y git

ENV PYTHONPATH "/workspace/dlr/lib/python/"

WORKDIR /workspace
