FROM nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04 AS base
LABEL maintainer "Amazon SageMaker Neo <aws-neo-ai@amazon.com>"

# Environment
ENV DEBIAN_FRONTEND noninteractive

# Install all basic requirements
RUN apt-get update && \
    apt-get install -y python3 python3-dev python3-setuptools curl ca-certificates build-essential && \
    apt-get install -y gcc libtinfo-dev zlib1g-dev build-essential wget libedit-dev libxml2-dev && \
    apt-get install -y antlr4 && \
    apt-get install -y python3-pip && \
    apt-get install -y gnupg && \
    apt-get install -y git

RUN wget https://cmake.org/files/v3.17/cmake-3.17.2-Linux-x86_64.sh \
    && bash cmake-3.17.2-Linux-x86_64.sh --skip-license --prefix=/usr/local

RUN pip3 install sklearn pytest

# Default entry-point to use if running locally
# It will preserve attributes of created files
# COPY entrypoint.sh /scripts/

ENV LD_LIBRARY_PATH=/packages/TensorRT-7.0.0.11/lib:$LD_LIBRARY_PATH

WORKDIR /workspace
# ENTRYPOINT ["/scripts/entrypoint.sh"]
